In [7]:
from EMCost import *
import pennylane as qlm

num_input_qubits=4
output_qubits=4
n_trash_qubits=0
operator_support=[]
operator_support_probs=0
operator_translation_invariance_Q=0
operator_support_max_range=0

set_global( num_input_qubits,
            output_qubits,
            n_trash_qubits,
            operator_support,
            operator_support_probs,
            operator_translation_invariance_Q,
            operator_support_max_range,
            use_jax=False)

dvc = qml.device('default.mixed', wires=num_input_qubits, shots=None)

@qml.qnode(dvc,interface='jax')
def trainer(w,dm):
    print(dm)
    qml.QubitDensityMatrix(dm, wires=dvc.wires)
    return qml.state()
input_states=[]


In [9]:

X=[]
for a in range(2**num_input_qubits):
    a=jnp.array(list(map(int,list(format(a,f'0{num_input_qubits}b')))))
    X.append(jnp.outer(a, a))
    input_states.append(jnp.outer(a, a))

f =cost_fn_EM(X,trainer,input_states)
f([1])


# print(format(a,f'0{num_input_qubits}b'),format(b,f'0{num_input_qubits}b'))

# cost_fn_EM(input_states,trainer,input_states)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


c:\Users\forazi\.conda\envs\forazi\Lib\site-packages\autoray\autoray.py:81: UserWarning: Explicitly requested dtype <class 'numpy.complex128'> requested in asarray is not available, and will be truncated to dtype complex64. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  return func(*args, **kwargs)


ValueError: Density matrix must be of length (2**wires, 2**wires)